# Generated by Django 5.1.7 on 2025-05-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="description",
        ),
        migrations.RemoveField(
            model_name="note",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="note",
            name="uploaded_by",
        ),
        migrations.AddField(
            model_name="note",
            name="content",
            field=models.TextField(default="Default content"),
        ),
    ]
