# Generated by Django 5.1.7 on 2025-05-06 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_note_uploaded_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="content",
        ),
        migrations.AddField(
            model_name="note",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="note",
            name="subject",
            field=models.CharField(
                choices=[
                    ("maths", "Mathematics"),
                    ("physics", "Physics"),
                    ("cs", "Computer Science"),
                    ("other", "Other"),
                ],
                default="maths",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="note",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
