# Generated by Django 5.1.7 on 2025-05-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_customuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="semester",
            field=models.CharField(default="1", max_length=100),
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
