# Generated by Django 5.1.7 on 2025-05-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_note_semester_delete_customuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="semester",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="note",
            name="subject",
            field=models.CharField(max_length=100),
        ),
    ]
