# Generated by Django 5.1.7 on 2025-05-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_note_downloads_note_upload_date_note_views_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
